services:
  frontend:
    build: .
    ports:
      - "80:4173" 
    networks:
      - salyte_backend_salyte
    environment:
      - NODE_ENV=production

networks:
  salyte_backend_salyte:
    external: true